cohortAttend/force-app/main/default/objects/Communion__c/Communion__c.object-meta.xml
<CustomObject>
    <label>Communion</label>
    <nameField>
        <label>Communed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohortAttend/force-app/main/default/objects/Communion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Contact this record is related to</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Communed_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Communion__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Date Communed</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Contact/fields/Worship_Cohort__c.field-meta.xml
<CustomField>
    <fullName>Worship_Cohort__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this contact to be added to the Worship Cohort?</description>
    <inlineHelpText>Is this contact to be added to the Worship Cohort?</inlineHelpText>
    <label>Worship Cohort</label>
    <type>Checkbox</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Group_1__c/Group_1__c.object-meta.xml
<CustomObject>
    <label>Group 1</label>
    <nameField>
        <label>Group 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohortAttend/force-app/main/default/objects/Group_2__c/Group_2__c.object-meta.xml
<CustomObject>
    <label>Group 2</label>
    <nameField>
        <label>Group 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohortAttend/force-app/main/default/objects/Group_2__c/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <label>Attendance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Group_3__c/Group_3__c.object-meta.xml
<CustomObject>
    <label>Group 3</label>
    <nameField>
        <label>Group 3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group 3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohortAttend/force-app/main/default/objects/Worship_Service__c/Worship_Service__c.object-meta.xml
<CustomObject>
    <label>Worship Service</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Worship Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worship Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohortAttend/force-app/main/default/objects/Worship_Service__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Date of Worship Service</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Worship_Service__c/fields/Number_in_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Number_in_Attendance__c</fullName>
    <inlineHelpText>Attendance number</inlineHelpText>
    <label>Number in Attendance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Worshipper__c/Worshipper__c.object-meta.xml
<CustomObject>
    <description>Contact worship attendance</description>
    <label>Worshipper</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Worshipper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worshippers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cohortAttend/force-app/main/default/objects/Worshipper__c/fields/Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Contact_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Lookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Worshippers</relationshipLabel>
    <relationshipName>Worshippers</relationshipName>
    <type>Lookup</type>
</CustomField>

cohortAttend/force-app/main/default/objects/Worshipper__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Date attended worship</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

cohortAttend/force-app/main/default/classes/CohortAttendanceController.cls
public with sharing class CohortAttendanceController {

    @AuraEnabled(cacheable=true)
    public static List<Contact> getWorshipCohortContacts(Date serviceDate) {
        return [
            SELECT Id, FirstName, LastName
            FROM Contact 
            WHERE Worship_Cohort__c = true
        ];
    }

    @AuraEnabled
    public static Worshipper__c markContactPresent(Id contactId, Date serviceDate) {
        // Assume contactId is a valid ID of an existing Contact
        Worshipper__c newWorshipper = new Worshipper__c(Contact_Lookup__c = contactId, Date__c = serviceDate);
        insert newWorshipper;
        return newWorshipper;
    }
    
    @AuraEnabled
    public static Worship_Service__c createWorshipAttendanceRecord (Date serviceDate, Integer totalAttendance) {
        try {
            Worship_Service__c attendanceRecord = new Worship_Service__c (
                Date__c = serviceDate,
                Number_in_Attendance__c = totalAttendance
            );
            insert attendanceRecord;
            return attendanceRecord;
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static Contact createWorshipCohortContact(String firstName, String lastName) {
    Contact newContact = new Contact(FirstName = firstName, LastName = lastName, Worship_Cohort__c = true);
    insert newContact;
    return newContact;
    }

    @AuraEnabled
    public static Communion__c createCommunionRecord(Id contactId, Date serviceDate){
        try {
            // Create a new Communion record with the Contact ID and Service Date
            Communion__c communionRecord = new Communion__c(
                Date__c = serviceDate, 
                Contact__c = contactId,
                Name = 'Communion for : ' + contactId // Set the Name field using the Contact ID
            );
    
            // Insert the Communion record into the database
            insert communionRecord;
    
            // Return the newly created Communion record
            return communionRecord;
        } 
        catch (Exception e) {
            // Handle exceptions
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void unmarkContactPresent(Id worshipperId) {
        delete [SELECT Id FROM Worshipper__c WHERE Id = :worshipperId LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Worship_Service__c> getWorshipServiceRecords() {
        return [SELECT Id, Date__c, Number_in_Attendance__c FROM Worship_Service__c ORDER BY Date__c DESC];
    }

    @AuraEnabled
    public static void addGroupAttendanceRecord (String groupNameInput, Date input1, Integer attendanceTotalInput) {
        List<Group_1__c> newGroup1List = new List<Group_1__c> (); 
        List<Group_2__c> newGroup2List = new List<Group_2__c> ();  
        List<Group_3__c> newGroup3List = new List<Group_3__c> ();  
        
        try {
        if(groupNameInput == 'Group 1') {
            Group_1__c newGroup1 = new Group_1__c(
            Date__c = input1,
            Attendance__c = attendanceTotalInput,
            Name = 'Group 1');
            newGroup1List.add(newGroup1);
        }
        else if (groupNameInput == 'Group 2') {
            Group_2__c newGroup2 = new Group_2__c(
            Date__c = input1,
            Attendance__c = attendanceTotalInput,
            Name = 'Group 2');
            newGroup2List.add(newGroup2);
        }
        else if(groupNameInput == 'Group 3') {
            Group_3__c newGroup3 = new Group_3__c(
            Date__c = input1,
            Attendance__c = attendanceTotalInput,
            Name = 'Group 3');
            newGroup3List.add(newGroup3);
        }
        
        if (!newGroup1List.isEmpty()) {
            insert newGroup1List;
        }
        if (!newGroup2List.isEmpty()) {
            insert newGroup2List;
        }
        if (!newGroup3List.isEmpty()) {
            insert newGroup3List;
        }
        }   
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
            
        }
    }
    @AuraEnabled
    public static Group_Member__c markGroupMemberPresent(Id contactId, Date serviceDate, String groupName) {
        Worshipper__c newWorshipper = new Worshipper__c(Contact_Lookup__c = contactId, Date__c = serviceDate);
        insert newWorshipper;
        return newWorshipper;
    }
    
}